environment:
  COVERALLS_PARALLEL: true
  COVERALLS_REPO_TOKEN:
    secure: dZWaKkr6xvP+aDksWLreF0p0L7LLiybUY2bUgGAqc3m/uVWHszncQcsXe5X1+rrf
  matrix:
    - PYTHON: "C:\\Python36-x64"
      TOXENV: py36
    - PYTHON: "C:\\Python37-x64"
      TOXENV: py37
    - PYTHON: "C:\\Python38-x64"
      TOXENV: py38

install:
  - "%PYTHON%\\python.exe -m pip install wheel tox codecov coveralls"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\Scripts\\coverage xml --ignore-errors"
  - "%PYTHON%\\Scripts\\codecov --required -X gcov pycov search -f coverage.xml --flags %TOXENV:-= % windows"

artifacts:
  - path: dist\*

matrix:
  fast_finish: true
