codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 10
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
