name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pep517 and twine
      run: python -m pip install pep517 twine --user
    - name: Build a binary wheel and a source tarball
      run: python -m pep517.build --source --binary --out-dir dist/ ./
    - name: twine check
      run: python -m twine check dist/*
    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.event.ref, 'refs/heads/master')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.testpypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
